### ISSUE TITLE
documentation for changing gif image size

### ISSUE THREAD

**Issue by kcandrews** [thomasp85/gganimate#10]
Cool package!

I couldn't find a way to change the size of the gif image. Could you add some documentation to show how that is done?

**Comment by ginolhac** [comment]
using the options from `animation` works well

```
gg_animate(p, ani.width=800, ani.height=1000)
```

**Comment by kcandrews** [comment]
Thanks, that works for me as well. Reading the README again, that seems clear. Although it didn't last night. Perhaps adding another example for this common case would be helpful.

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
