### ISSUE TITLE
Cannot animate boxplot

### ISSUE THREAD

**Issue by shabbychef** [thomasp85/gganimate#13]
It seems there is no `frame` in the `data` built for boxplots. Here is a MWE:

```
# MWE of boxplot w/ gganimate
nsamp <- 10000
set.seed(1234)
fakedf <- data.frame(x=ceiling(rnorm(nsamp,sd=2)),
                     y=rnorm(nsamp),
                     f=ceiling(runif(nsamp,min=0,max=7)))

library(ggplot2)
library(gganimate)
# this works:
ph <- ggplot(fakedf,aes(x=x,y=y,frame=f)) + geom_point()
gg_animate(ph)

# this does not:
ph <- ggplot(fakedf,aes(x=x,y=y,group=x,frame=f)) + geom_boxplot()
gg_animate(ph)
```

Here is the response:

```
Error in gg_animate(ph) : 
  No frame aesthetic found; cannot create animation
```

Digging into the code, there is no `frame`:

```
blt <- ggplot_build(ph)
colnames(blt$data[[1]]) 
```

```
 [1] "ymin"       "lower"      "middle"     "upper"      "ymax"       "outliers"   "notchupper" "notchlower" "x"          "group"      "PANEL"      "ymin_final"
[13] "ymax_final" "xmin"       "xmax"       "weight"     "colour"     "fill"       "size"       "alpha"      "shape"      "linetype"  
```

```
'frame' %in% colnames(blt$data[[1]]) 
```

```
FALSE
```

**Comment by wjhrdy** [comment]
I'm getting the same error for geom_histogram, geom_density, and geom_freqpoly even if I specify frame in aes().

**Comment by aleixdorca** [comment]
I had the same problem. In my case it also affected other geoms like geom_density, geom_bar. The solution that worked for me was to convert the frame variable to a factor.

**Comment by michdn** [comment]
I am getting the same error in geom_polygon (Warning: Ignoring unknown aesthetics: frame). I'm trying to use a date (weekly date values) as my frame variable.  
I tried a) turning the date into a factor directly: as.factor(Date), 
b) turning the dates into a numerical sequence: cut(Date, "week", labels = FALSE),
c) turning the numerical sequence (int) into a factor.  
I haven't found anything that works for me so far. Any ideas are appreciated!

**Comment by mgagliol** [comment]
I confirm the issue also for geom_violin, can it be solved in gganimate? or is a solution possible only in ggplot2? Thanks

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
