### ISSUE TITLE
Cannot change resolution of output

### ISSUE THREAD

**Issue by phil-martin-research** [thomasp85/gganimate#15]
Great work on the package, it's really useful.

I'm putting together a gif to use in a presentation but can't work out if I can alter the resolution of the output from gg_animate(). Ideally, I'd like to be able to have a full screen .gif that isn't grainy.

Is there any way to alter the resolution of outputs in gganimate?

**Comment by yeedle** [comment]
Use the `ani.width` and `ani.height` arguments. https://github.com/dgrtwo/gganimate/issues/10

**Comment by gedankenstuecke** [comment]
Small hint: this only works if you're not specifying a file to write to. Just had this issue. For example `gg_animate(plot,"output.mp4",ani.width=800, ani.height=400)` will fail with an error. 

For this you'll have to specify the width & height in `ani.options`, e.g.

```
ani.options(ani.width=800, ani.height=400)
gg_animate(plot,"output.mp4") 
```

Happy to update the docs to reflect that if that's wished.

**Comment by yeedle** [comment]
@gedankenstuecke, first, if you explicitly specify the `filename` argument it will work.

``` r
gg_animate(plot, filname = "output.mp4", ani.width=800, ani.height=400)
```

Alternatively, you can pass in the filename as the last argument, and it will work as well.

``` r
gg_animate(plot, ani.width=800, ani.height=400, "output.mp4")
```

**Comment by gedankenstuecke** [comment]
Ah, thanks! Then nevermind!

**Comment by jrosen48** [comment]
Hmm, I tried this, and got the following error message:

```
>gganimate(gg, filename = "test.gif", ani.width=1000, ani.height=800)
Error in check.options(new, name.opt = ".X11.Options", envir = .X11env) : 
  invalid argument names ‘ani.width’, ‘ani.height’ in 'grDevices::png(..., res = dpi, units = "in")'
```

**Comment by yeedle** [comment]
Yes, `gganimate` was updated since then. Instead, try this:

```r
animation::ani.options(ani.width = 1000, ani.height = 800)
gganimate(gg, filename = "test.gif")
```

**Comment by xgirouxb** [comment]
AFAIK, given that the default for `grDevices::png()` is 72 ppi, adjusting the number of pixels (via `ani.width` and `ani.height`) used to draw an image only defines the dimensions of the output, not the resolution of the output. I fiddled around quite a bit and my outputs always seemed way too grainy. I googled around and found the following solution using the `ani.res` argument:

```r
animation::ani.options(ani.width = 1000, ani.height = 800, ani.res = 300)
gganimate(gg, filename = "test.gif")
```

While this works great for me, the solution isn't obvious because `ani.res` is not listed in the [documentation currently hosted on CRAN](https://cran.r-project.org/web/packages/animation/animation.pdf) (dated 2017-03-30). It seems that the argument is brand new and is only included in the latest update of the `animation` package (rolled out a month ago). See the following conversation and feature request: https://github.com/yihui/animation/issues/99

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
