### ISSUE TITLE
could not find function "gganimate"

### ISSUE THREAD

**Issue by pgvelazquez87** [thomasp85/gganimate#150]
Hello,

I installed gganimate after installing ImageMagick, however, when I run gganimate there's an error message: Error in gganimate(map) : could not find function "gganimate"

Could you please help me with this?

Thank you.

**Comment by maoa20** [comment]
I have the same problem, i dont know how to fix it.

  p2 <- ggplot(gapminder, mapping = aes(x = gdpPercap, y = lifeExp, size = pop)) +
    geom_point() +
    geom_point(aes(frame = year), color = "violetred") +
    scale_x_log10()
  
  gganimate(p2)

Error in gg_animate(p2) : could not find function "gganimate"

**Comment by pgvelazquez87** [comment]
As a follow-up: I installed a modified package from here: 
devtools::install_github("nteetor/gganimate") and now it works by typing 'gganimate::gg_animate(p)'

Anyway, I´d greatly appreciate your help to understand more about the differences between thomasp85 and nteetor packages.

Thanks in advance.

**Comment by thomasp85** [comment]
The fork you’re referencing is based on the old version, whereas this one is a complete rewrite of the package with a new API. As discussed in the readme the old and new api is not compatible, so any example that uses frame as an aesthetic will no longer work

**Comment by pgvelazquez87** [comment]
Thank you for your reply Thomas. Any advice to avoid the aforementioned problem? This only appears in the latest version. Thank you.

**Comment by thomasp85** [comment]
The `gganimate` function no longer exists as it was part of the old API. I suggest you get acquainted with the new API through the documentation and the examples in the wiki

**Comment by CharlesBordet** [comment]
@thomasp85 This is confusing as your other library tweenr recommends using `gganimate` and provides examples that use this obsolete function `gganimate`.

**Comment by thomasp85** [comment]
You are right - I haven’t had time (or prioritised) updating references to the old api in my other packages

**Comment by davidfombella** [comment]
p <- pitch_plot(68, 105) +
  geom_polygon(data = filter(data_hull, team == 'team A'), aes(x, y, frame = .frame), fill = 'red', alpha = 0.4) +
  geom_polygon(data = filter(data_hull, team == 'team B'), aes(x, y, frame = .frame), fill = 'blue', alpha = 0.4) +
  geom_point(data = filter(data, str_detect(team, 'team')), aes(x, y, group = player, fill = team, frame = .frame), shape = 21, size = 6, stroke = 2) +
  geom_point(data = filter(data, team == 'ball'), aes(x, y, frame = .frame), shape = 21, fill = 'dark orange', size = 4) +
  scale_fill_manual(values = c('team A' = 'red', 'team B' = 'blue')) +
  geom_text(data = filter(data, str_detect(team, 'team')), aes(x, y, label = player, frame = .frame), color = 'white') +
  guides(fill = FALSE)

animation::ani.options(ani.width = 735, ani.height = 476)
**gganimate(p, 'sequence_2.gif', interval = 0.05, title_frame = FALSE)**

**Could this be caused by using frame aesthetic?**

**Error in gganimate(p, "sequence_2.gif", interval = 0.05, title_frame = FALSE) : 
  could not find function "gganimate"**

SESSION INFO
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2.2       tweenr_1.0.0         gganimate_0.9.9.9999 forcats_0.3.0        stringr_1.3.1       
 [6] dplyr_0.7.6          purrr_0.2.5          readr_1.1.1          tidyr_0.8.1          tibble_1.4.2        
[11] ggplot2_3.0.0        tidyverse_1.2.1

**Comment by thomasp85** [comment]
There is no `gganimate()` function in gganimate

**Comment by Juliatree** [comment]
So how could we make a similar animate figure if there is no gganimate() function. Is there any other function could carry it out?

**Comment by bjce** [comment]
Also having trouble with the function `gganimate(p, "output.mp4")`, getting the traceback: `Error in gganimate(p) : could not find function "gganimate"`. By the way thank you very much for writing the package!

**Comment by thomasp85** [comment]
Please see the last section of the README

**Comment by bjce** [comment]
@Juliatree So I think that, after generating the animation **[1]**:

```
p2 <- ggplot(gapminder, mapping = aes(x = gdpPercap, y = lifeExp, size = pop)) +
geom_point() +
geom_point(aes(frame = year), color = "violetred") +
scale_x_log10()
```
if you want to save in a `gif` format, simply write **[2]**:
```
anim_save("/path/to/your/animation/animation_to_be_saved.gif")
```

That worked for me. 

If you want to save the animation to an `mp4` format (and not `gif` format), write the following **[3]** (instead of **[2]**):
```
animate(p2, renderer = ffmpeg_renderer())
anim_save("/path/to/your/animation/animation_to_be_saved.mp4")
```
