### ISSUE TITLE
finer control for title_frame

### ISSUE THREAD

**Issue by davharris** [thomasp85/gganimate#19]
This is an excellent package; thanks for making it.

I'm making an animation where `frame` is numeric. Currently, the number of digits included in the title_frame varies depending on how many digits after the decimal point are nonzero. As the width of the title changes, the digits jump around and everything becomes difficult to read.

Ideally, I'd like to be able to do something like pass a function of `frame` to either `gg_animate` or to `ggtitle`, so that I could control the text that is generated. 

If this is not currently possible (I didn't see the option in `?gg_animate`), would it be feasible to alter gganimate to accommodate this use? Thanks in advance

**Comment by nteetor** [comment]
@davharris over at [nteetor/gganimate](https://github.com/nteetor/gganimate), I updated the package such that `gg_animate` can now accept a formula as the `title_frame` argument. 

The below example demonstrates this new functionality, 

``` R
library(ggplot2)
p <- ggplot(iris, aes(Sepal.Length, Species, frame = Petal.Length)) +
  geom_point()
gg_animate(p, title_frame = ~ round(., 0))
```

The `.` refers to each frame value, so in the example each value of `Petal.Length` will be rounded to 0 decimal places when the frame titles are constructed. 

Of course the number of decimal places could be changed to suit your needs and I hope this change helps you solve your problem. I was also looking for finer frame title control and thought this was at least a temporary solution. You can install the updated gganimate using devtools, `devtools::install_github('nteetor/gganimate')`.

**Comment by davharris** [comment]
Thanks @nteetor!

**Comment by gsimchoni** [comment]
This should really be pulled into the official version.

**Comment by nteetor** [comment]
Now that the `rlang` package is out, there's probably a smoother way I could implement the update. I am not sure when I can research `rlang` more and make the change, but I will make it a TODO.

**Comment by gsimchoni** [comment]
Using your fork here:
http://giorasimchoni.com/2017/05/01/2017-05-01-federer-nadal-djokovic-and-murray-love/

**Comment by nteetor** [comment]
@gsimchoni super cool! Thank you for sharing, I am glad the utility is being put to good use.

**Comment by leaf-jing** [comment]
How about a function wrapper, a new aes frame.title will be used. arbitrary frame title possible

gganimate.dynamic.title <-  function(p = last_plot(), filename = NULL, saver = NULL, ...){
  gani <- gganimate(p, saver = saver, title_frame = F, ...)　# call without output file
  for (p in gani$plots)  p$plot$labels$title <- p$data[[1]]$frame.title[1]
  if (!is.null(filename)) { 
    gani$ani_opts <- NULL
    gani <- gganimate_save(gani, filename, saver, ...) # ..
  } 
  gani
}

**Comment by nteetor** [comment]
Is there an unspoken problem with the `title_frame` argument or `gg_animate` function? Or simply suggesting a new approach?

For those who do not want to install a fork of gganimate, a separate function is handy. However, in the long run I hope the new title functionality will be incorporated and make it onto CRAN.

**Comment by alistaire47** [comment]
A more general way to deal with this would be to find a way to allow parameterization of text fields, so the variable passed to `frame` could also be formatted and passed to `title`, `subtitle`, `caption`, `label` (this works already), etc., so the frame aesthetic could easily be formatted, rearranged, and even programmed with.

To make this pretty would require changing ggplot so it could accept `title`, etc. as aesthetics (because they're variables, not fixed strings, it should happen in `aes`), but given how `frame` is pulled out, it seems entirely possible to pull out text aesthetics similarly and internally pass the values to `labs`.

The remaining limitation is in setting labels for non-text aesthetics; `aes(x = foo)` and `labs(x = foo)` do unavoidably different things. I guess a more thorough version could be made by pulling out and running the `labs` parameters, but I suspect that would be more work.

If there's interest I could take a crack at a PR, but it might take me a while.

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
