### ISSUE TITLE
convert.exe is not found in the new version of ImageMagick

### ISSUE THREAD

**Issue by smalaichami** [thomasp85/gganimate#22]
Getting the following error while executing gg_animate function... 

I cannot find ImageMagick with convert = "convert"
but I can find it from the Registry Hive: C:\Program Files\ImageMagick-7.0.3-Q16
"C:\Program Files\ImageMagick-7.0.3-Q16\convert.exe"  -loop 0 -delay 10
    Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png
    Rplot8.png Rplot9.png Rplot10.png Rplot11.png Rplot12.png Rplot13.png

**Comment by Tmana** [comment]
Workaround:

Install ImageMagick and point R path to its folder with the executables:

Sys.setenv(PATH = paste("C:/Program Files/ImageMagick/bin",
                        Sys.getenv("PATH"), sep = ";"))

**Comment by josie-hughes** [comment]
The workaround suggested above does not work for me. convert.exe seems to be missing entirely from new versions of ImageMagick. This discussion seems relevant: http://www.imagemagick.org/discourse-server/viewtopic.php?t=29582. But I can't find a "Install legacy components" tickbox in installation. Help?

**Comment by tyokota** [comment]
The convert.exe binary file is in the portable zip version, which can be found on the download page: http://www.imagemagick.org/script/binary-releases.php 

![image](https://cloud.githubusercontent.com/assets/4334198/21193972/4529565a-c1d2-11e6-9073-0da8ac61bd45.png)

**Comment by josie-hughes** [comment]
Good. Thanks

**Comment by stephenbfroehlich** [comment]
There is also a checkbox in the DLL installer that is for "legacy" support that will install "convert".  That plus the above PATH edit works for me in Windows 7.

**Comment by yutannihilation** [comment]
It seems that we no longer need the desperate try with the old version of ImageMagick, as this PR is merged:

Using magick as default gif converter
https://github.com/yihui/animation/pull/98

Try the dev version of animation with `devtools::install_github("yihui/animation")`. Everything works fine (, at least for me).

**Comment by JohnsonBrent** [comment]
I'm late to the party but in case someone comes across this error (like I just did)... I found that using installr from within R to create the imagemagick installation did the trick of connecting gganimate to imagemagick:
`library(installr);
install.ImageMagick(URL = "http://www.imagemagick.org/script/binary-releases.php")
`

**Comment by danklotz** [comment]
@JohnsonBrent This tels me that the URL cannot be opened, i.e. "HTTP status was '404 Not Found'"

**Comment by JoeAmmar** [comment]
@danklotz That link is outdated. Try this instead:
install.imagemagick("https://www.imagemagick.org/script/download.php")

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)

**Comment by kumarkundan** [comment]
> Workaround:
> 
> Install ImageMagick and point R path to its folder with the executables:
> 
> Sys.setenv(PATH = paste("C:/Program Files/ImageMagick/bin",
> Sys.getenv("PATH"), sep = ";"))

How we can do for  windows...plz explain

**Comment by yutannihilation** [comment]
@kumarkundan This issue is too old, now you don't need the executable to use ImageMagick since there's magick package :)

**Comment by kumarkundan** [comment]
> @kumarkundan This issue is too old, now you don't need the executable to use ImageMagick since there's magick package :)

yes i followed @tyokota solution , it worked. THANKS for prompt response.
