### ISSUE TITLE
Warning during installation

### ISSUE THREAD

**Issue by ashgreat** [thomasp85/gganimate#25]
I'm getting these warning messages during installation.
`Warning: /private/var/folders/w0/zf6n6gbd2kd0jlvsm9hlb6kw0000gn/T/RtmpAZWgMX/devtoolsb03697ffe34/dgrtwo-gganimate-0e7b8ae/man/gganimate_save.Rd:19: unexpected RCODE '[pkg=ggplot2]{ggsave', expecting '{'
Warning: /private/var/folders/w0/zf6n6gbd2kd0jlvsm9hlb6kw0000gn/T/RtmpAZWgMX/devtoolsb03697ffe34/dgrtwo-gganimate-0e7b8ae/man/gganimate_save.Rd:20: unexpected RCODE '[pkg=animate]{saveVideo', expecting '{'
Warning: /private/var/folders/w0/zf6n6gbd2kd0jlvsm9hlb6kw0000gn/T/RtmpAZWgMX/devtoolsb03697ffe34/dgrtwo-gganimate-0e7b8ae/man/gganimate_save.Rd:20: unexpected '}'
Warning: /private/var/folders/w0/zf6n6gbd2kd0jlvsm9hlb6kw0000gn/T/RtmpAZWgMX/devtoolsb03697ffe34/dgrtwo-gganimate-0e7b8ae/man/gganimate_save.Rd:20: All text must be in a section`

But the package loads after this. When I use gganimate() to animate a plot, I get the following errors and warnings:

`sh: convert: command not found
Error in cmd.fun(sprintf("%s --version", convert), intern = TRUE) : 
  error in running command
I cannot find ImageMagick with convert = 'convert'
Error in file(file, "rb") : cannot open the connection
In addition: Warning messages:
1: In animation::im.convert(filenames[-1], basename(filename), extra.opts = opts,  :
  Please install ImageMagick first or put its bin path into the system PATH variable
2: In file(file, "rb") :
  cannot open file '/var/folders/w0/zf6n6gbd2kd0jlvsm9hlb6kw0000gn/T//RtmpAZWgMX/gganimate/fileb03520a3e08.gif': No such file or directory`

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
