### ISSUE TITLE
animation loops too early

### ISSUE THREAD

**Issue by drmowinckels** [thomasp85/gganimate#253]
I'm working on an animation that transitions at different ages. I've been using `transition_state` rather than time, as the label for transition time wasn't working nicely for me (label has lots of decimals despite the frame vector being an integer, this only happens when I use geom_polygon).

My frame variable goes from 4 to 93 . But the animation loops around frame 55, rather than 93. 

```
dt = expand.grid(list(Age = 4:93, 
                                     area=c("superior temporal", "pre central", "post central"))) %>% 
           as.data.frame %>% 
            mutate(thickness = sample(seq(1,5,by=.001), nrow(.), replace=T))


dt %>% 
ggplot(aes(x=area, y=thickness)) + 
geom_bar(stat="identity") +
 transition_states(Age, 1, 1) + 
labs(title='Age: {closest_state}')

```

![example](https://user-images.githubusercontent.com/14014329/50283555-7f3e5200-0456-11e9-85ec-2edde5ca17ad.gif)

**Comment by Victor-GY-Yu** [comment]
Can you provide a copy of the df?

**Comment by drmowinckels** [comment]
The code above has code to make the data.frame. the gis attached is made entirely with the code in the issue.

**Comment by Victor-GY-Yu** [comment]
Sorry, must have been a late night :-)

I'm guessing this is because there are too many frames for the default value (100) to look over, but @thomasp85 can probably describe it in better technical detail.

If you do something like this, which expands the number of frames available in the animation, it should work:

```
my_anim <- dt %>% 
ggplot(aes(x=area, y=thickness)) + 
geom_bar(stat="identity") +
 transition_states(Age, 1, 1) + 
labs(title='Age: {closest_state}')

animate(my_anim, nframes = 200, fps = 10)
```

![Imgur](https://i.imgur.com/wXrygQ2.gif)

**Comment by thomasp85** [comment]
As @VictorNautica writes this is simply because you do not have enough frames to both show each state and transition between them. One approach is to increase either `nframes` or `detail` in `animate()`. Another is to set `transition_length = 0` in `transition_states()`... For so many states using `transition_manual()` would also make sense...
