### ISSUE TITLE
Free scales

### ISSUE THREAD

**Issue by ronammar** [thomasp85/gganimate#28]
In `ggplot2`'s facets, there's an option to have `scales="free"`. Is there a way to have free scales in each frame of `gganimate`?

Full question posted on SO:
https://stackoverflow.com/questions/41026047/gganimate-with-changing-scales-axis-limits

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)

**Comment by ronammar** [comment]
Since I'm not a collaborator, I can't re-open this issue. Should I submit it again?

**Comment by dgrtwo** [comment]
Sorry about that, reopened!

**Comment by thomasp85** [comment]
This is possible using the different `view_*()` functions in the new version
