### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by zx8754** [thomasp85/gganimate#29]
In  README.md

> (Each of these requires ffmpeg, ImageMagick, or other such drivers to be installed on your computer: see the animation package documentation for more).

http://www.inside-r.org/packages/cran/animation/docs/animation

**Comment by brendanhoganvt** [comment]
Same with the link further down to `ani.options`:

> Finally, note that you can control your animation with the same options described in ani.options, passed directly to gganimate or to ani.options beforehand.

For `ani.options`, this seems like the place to go: https://yihui.name/animation/example/ani-options/

For the top-level package documentation, see: https://yihui.name/animation/example/animation-package/ or even https://yihui.name/animation/ (which is the url from the description on CRAN)

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
