### ISSUE TITLE
Cannot use the interval argument properly

### ISSUE THREAD

**Issue by kanishkamisra** [thomasp85/gganimate#31]
```r
library(gapminder)
library(ggplot2)
library(gganimate)
library(tweenr)
theme_set(theme_bw())
#had to use this because %>% isn't recognized for some reason
library(magrittr)

tw <- gapminder %>%
  split(.$year) %>%
  tweenr::tween_states(tweenlength = 5, statelength = 0,
                        ease = "linear",
                        nframes = 25)

p <- ggplot(tw, aes(gdpPercap, lifeExp, size = pop / 1e6, color = continent, frame = .frame)) +
  geom_point(alpha = 0.7) +
  scale_x_log10(breaks = c(400, 1000, 4000, 10000, 40000, 100000)) + 
  scale_size_continuous(range = c(1,13))

p

gganimate(p)
#this doesnt work
gganimate(p, interval = .2)
```

The error that I get is: 

```
Error in grDevices::png(..., res = dpi, units = "in") : 
  unused argument (interval = 0.2)
```

**Comment by filipwastberg** [comment]
I have the same issue, but you can set the interval in ani.options through the animation package.
```
library(animation)
ani.options(interval = .2)
```

Did the trick for me!

**Comment by kgweber-sag** [comment]
On the other hand, 

`ani.options(interval = .1, ani.width= 600, ani.height = 400)`

did *not* work for setting the dimensions of the images.

Neither did:

`ani.options(interval = .1, width= 600, height = 400)`

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
