### ISSUE TITLE
cowplot dependency

### ISSUE THREAD

**Issue by jonocarroll** [thomasp85/gganimate#32]
`cowplot` is now a required package as per the new change in [saving.R](https://github.com/dgrtwo/gganimate/blob/2cb5ced0235b181d9ec2fdd2d8f31d4d8d985cbc/R/saving.R#L102) and should be in `DESCRIPTION`.

**Comment by jarodmeng** [comment]
This essentially also makes `gganimate` depend on R >= 3.3.0 since `cowplot` depends on it. Is this a must? I have R 3.2.2 installed and I cannot run `gganimate` because of this.

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
