### ISSUE TITLE
how to apply different transitions to different layers

### ISSUE THREAD

**Issue by shawnchenx6** [thomasp85/gganimate#325]
I want apply different transitions to different layers. I am quite confused by the different transition  functions and how groups influence the outcome.
 what code should I use if I want to do the following animation

![gif](https://github.com/ShawnChen1996/Files/blob/master/file2b0057ad7059.gif?raw=true)

 **the gray points remain the same while the fitted red line is revealed with a blue short line representing the local average and dark points showing which data is used to generate the local estimate** 
the grey points remain the the same 
the `transition_reveal` should be applied to the red line and blue dash layer
the `transition_time` should be applied to the dark points.
How can I do it? and can you discuss the logic behind? 
thank you so much!

====
code to generate the static graph is as follows
```
library(tidyverse)
library(dslabs)
library(gganimate)

data("polls_2008")
span <- 3.5
tmp <- polls_2008 %>%
     crossing(center = polls_2008$day) %>%
     mutate(dist = abs(day - center)) %>%
     filter(dist <= span) 

fit <- with(polls_2008, ksmooth(day, margin, kernel="box", x.points = day, bandwidth = span))
bin_fit <- data.frame(x = fit$x, .fitted=fit$y)

dat = left_join(tmp,bin_fit, by=c('day'='x'))

ggplot(dat, aes(day, margin, group=center))+
     geom_smooth(method = "lm", formula=y~1, se = FALSE) +
     geom_line(aes(x=day, y = .fitted), color = "red") +
     geom_point(aes(day, margin),size = 3, alpha = .5, color = "grey") 

```

**Comment by bastianolea** [comment]
I have the same issue. I can animate a `geom_line` graph with `transition_reveal`, but if I also want to plot `geom_point` over the same lines (i.e., both gems animating along the same x axis values), the points do not get animated, despite specifying `enter_fade()` and such (they just appear without any tweening). 

I think the problem lies in not being able to use two transition modes in the same graph (in my case, using `transition_reveal` for `geom_line` and `transition_states` for `geom_point`). 

Is there a workaround, or is this not yet implemented?

**Comment by VaibhavSingh033** [comment]
Any update on this ?? Same issue

**Comment by nickresnick** [comment]
know follow ups are annoying, but want to follow up on this as it's been a few months since the last follow up :)

**Comment by thomasp85** [comment]
You cannot use different transitions within the same animations. I cannot say if this will appear in the future (but I expect not)
