### ISSUE TITLE
dependencies error

### ISSUE THREAD

**Issue by waholulu** [thomasp85/gganimate#33]
It reports dependencies error while I have all the packages it requires.

Downloading GitHub repo dgrtwo/gganimate@master
from URL https://api.github.com/repos/dgrtwo/gganimate/zipball/master
Installing gganimate
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/wahol/AppData/Local/Temp/Rtmpc5l8dZ/devtools34ac5b20655c/dgrtwo-gganimate-0e7b8ae"  \
  --library="C:/Users/wahol/OneDrive/文档/R/win-library/3.3" --install-tests 
ERROR: dependencies 'plyr', 'ggplot2', 'animation', 'base64enc', 'htmltools', 'withr' are not available for package 'gganimate'
* removing 'C:/Users/wahol/OneDrive/文档/R/win-library/3.3/gganimate'
Error: Command failed (1)

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
