### ISSUE TITLE
Gapminder example results in immediate error

### ISSUE THREAD

**Issue by phillyo** [thomasp85/gganimate#34]
Running the gapminder example, I get the following error:

sh: convert: command not found
Error in cmd.fun(sprintf("%s --version", convert), intern = TRUE) : 
  error in running command
Error in file(file, "rb") : cannot open the connection

I'm running R version 3.3.2 (2016-10-31), on an apple computer (x86_64-apple-darwin13.4.0) running macOS Sierra (10.12.2)

thanks!

**Comment by filipwastberg** [comment]
Have you installed ImageMagick?

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
