### ISSUE TITLE
plot.title colour gets ignored by gganimate

### ISSUE THREAD

**Issue by ottlngr** [thomasp85/gganimate#35]
Setting the title colour with `plot.title = element_text(colour = col)` gets ignored by gganimate.

Example:

    library(ggplot2)
    library(gapminder)

    p <- ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, color = continent, frame = year)) +
      geom_point() +
      scale_x_log10() +
      theme(plot.title = element_text(colour = "red")) + 
      labs(title = "Title")

    gganimate(p)

**Comment by filipwastberg** [comment]
Yeah, this was not an issue in the early life off gg_animate()? https://beta.rstudioconnect.com/kamermanpr/central-limit-n-large-numbers/central-limit-n-large-numbers.html#

**Comment by filipwastberg** [comment]
@ottlngr do you have the same issue when changing the output to .mp4 or .html? This only occurs in .gif for me.

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
