### ISSUE TITLE
map is gigantic when animated but not when plotted

### ISSUE THREAD

**Issue by jrosen48** [thomasp85/gganimate#40]
When I create a plot of a map using `ggplot2` and `geom_map()`, the map appears normal-sized:

<img width="738" alt="screen shot 2017-02-27 at 10 47 23 am" src="https://cloud.githubusercontent.com/assets/4596214/23368009/5a074e36-fcda-11e6-9fb6-27766ab4bbd3.png">

However, when I animate it, it's too large to appear in the viewer:

<img width="744" alt="screen shot 2017-02-27 at 10 48 42 am" src="https://cloud.githubusercontent.com/assets/4596214/23368020/6045234a-fcda-11e6-93e5-ace75bd999c6.png">

How can I address this?

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
