### ISSUE TITLE
Axis limits with view_step_manual

### ISSUE THREAD

**Issue by ferenci-tamas** [thomasp85/gganimate#408]
Consider the following simple example:

```
dat <- data.frame(x = 1:100, y = 0)
ggplot(dat, aes(x = x, y = y)) + geom_point() + transition_time(x) +
  view_step_manual(xmin = dat$x-3, xmax = dat$x+3, ymin = -3, ymax = 3, pause_length = 0)
```

I expected the point to be in the middle, as the x axis limits go from its position minus 3 to plus 3 (i.e., symmetrically), yet, it is displayed to the right of the center of the plot.

**Comment by thomasp85** [comment]
The issue is a bit non-obvious, but since the view has `wrap = TRUE` it includes an additional stage where it wraps back to the beginning. This means that all your windows doesn't match the data exactly. In general `view_step()` and `view_step_manual()` are mostly made to be paired with `transition_states()` as it can be difficult to match them up with other transitions (as you see here)...

`view_follow()` is a better approach but it should be expanded so that the range can be modified before use (to allow what you are basically doing and adding a padding of 3 around the data range)
