### ISSUE TITLE
cannot gganimate my plot due to ImageMagick 

### ISSUE THREAD

**Issue by loukesio** [thomasp85/gganimate#41]
Hello everyone 

everytime that i try to gganimate my image i take this error

'"C:\Program Files\ImageMagick-7.0.5-Q16\convert.exe"' is not recognized as an internal or external command,
operable program or batch file

do you have any idea what should i do ?

Best,

**Comment by danielmcintosh1** [comment]
I solved this by installing the 2013 C++ redistributable, restarting my computer and then re-runing the plotting code. I have a Windows 10 machine that was not compatible with newest ImageMagick

**Comment by loukesio** [comment]
Thanks a lot Daniel 
I ll try that

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
