### ISSUE TITLE
Thoughts on a CRAN / tagged release?

### ISSUE THREAD

**Issue by rpodcast** [thomasp85/gganimate#42]
I'm a big fan of the package and have begun exploring it for my projects.  I'd like to have this package installed in our R installation at work, but we typically install a release of a package either from CRAN or a tagged version fromthe GitHub repo.  Have you thought about making at least a tagged release of the package?  

Side note: It was great seeing you again at `rstudio::conf` and would like to have you on a future R Podcast episode soon!  Let me know if you'd like to discuss further.

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
