### ISSUE TITLE
cannot find ImageMagick with convert = "convert"

### ISSUE THREAD

**Issue by AlexYoung757** [thomasp85/gganimate#45]
I have run gganimations on Windows 8.1, R 3.4.0. when i run function gganimation(). the error as follow:
I cannot find ImageMagick with convert = "convert"
but I can find it from the Registry Hive: D:\ImageMagick\ImageMagick-7.0.5-Q16

the i try do some operations:
> system("convert -version")
Invalid drive specification.
Warning message:
running command 'convert -version' had status 4

> shell("convert -version")
Invalid drive specification.
Warning message:
 
how can i solve this problem

**Comment by espinielli** [comment]
I had the same.
I think this is a symptom of name clash with MS Windows' own `convert.exe` under `C:\WINDOWS\system32`

**Comment by espinielli** [comment]
I applied what mentioned in #22 (prepend PATH with ImageMagick installation path) and now the right `convert` can be found.

**Comment by AlexYoung757** [comment]
@espinielli thank you for your help , i have solve this problem

**Comment by AshPrasad** [comment]
Error showing up in my code
C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ocstringham** [comment]
try this: first load animation package

`library(animation)`

then add add ani.options parameter into the gganimate function:
`gganimate(p, ani.options(convert = 'path/to/convert.exe'))`

**Comment by hamnsannah** [comment]
Does anyone know how to find the correct file path for a Linux installation for this needed file?  I'm on Ubuntu 16.04.  I've looked around many of the directories and can't find either convert.exe or magick.exe.  I did install the libmagick++dev library as directed in the `magick` [vignette ](https://cran.r-project.org/web/packages/magick/vignettes/intro.html)

**Comment by popovs** [comment]
@hamnsannah this is likely because you didn't check the "Install legacy files" checkbox in the installer. `convert.exe` doesn't exist in the newer versions of ImageMagick. Try using homebrew for Linux to install ImageMagick for you - made everything super clean and easy on OSX for me: **http://linuxbrew.sh/**

As for me this thing just is not working on Windows. I've installed the legacy files, added the ImageMagick directory to my Path, tried using `installr` to install the files (as suggested here #22 ) to no avail. Here's what I get:

`gganimate(p,  interval=0.2, ani.options(convert = "C:/Program Files/ImageMagick-7.0.7-Q16/convert.exe"))`
`> Error in savers[[saver]] : no such index at level 1`

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
