### ISSUE TITLE
How could I suppress the rendering progress message?

### ISSUE THREAD

**Issue by zhengchencai** [thomasp85/gganimate#455]
Hi there,

May I ask if there is a way to suppress the rendering progress message? It is very helpful in most cases but it's not necessary to print them in HTML output from knitr. It seems I need to hack this line https://github.com/thomasp85/gganimate/blob/299fd586ce6c0ec2571dc0a07c8986c1317292f9/R/renderers.R#L114 but I wonder if there is an argument when using ```animate()``` function. Thank you very much. 

Rendering [==================================================================>---------------------] at 10 fps ~ eta: 1s

**Comment by thomasp85** [comment]
The progress bar is provided through the progress package. You have a global option `progress_enabled` which, if set to `FALSE` will suppress all showing of the progress bar

**Comment by cloudy-sfu** [comment]
It takes me 1 hour to find this solution when I suffer from the progress bar because it fills my screen. I hope suppressing it can be a default behavior in the future.

![image_2023-05-01_12-02-19](https://user-images.githubusercontent.com/41314224/235385007-bdc0f5e5-0bef-4f21-8644-fb384c9e0de3.png)
