### ISSUE TITLE
tar.gz file for installation

### ISSUE THREAD

**Issue by stefan-jovanovski** [thomasp85/gganimate#48]
Hello, 

In continuation of the topic I opened on SO:

https://stackoverflow.com/questions/44945455/issue-with-package-installation-of-gganimate?noredirect=1#comment76866407_44945455

I was wondering if you have a .tar.gz file of the package? 

I've been stugeling to install the package behind a coreporate firewall for couple of hours now. 

Many thanks and best regards,

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
