### ISSUE TITLE
gganimate error : convert: unable to open image 'Rplot1.png'....

### ISSUE THREAD

**Issue by debgger** [thomasp85/gganimate#49]
Hello, When I run the following code:

gganimate(multiples_chart, "multiples.gif", ani.width = 750, ani.height = 500, interval = 0.2)

I get the following **error**:

Executing: 
"convert -loop 0 -delay 20 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png
    Rplot8.png Rplot9.png "multiples.gif""
**convert: unable to open image 'Rplot1.png': No such file or directory @ error/blob.c/OpenBlob/3093.
convert: unable to open file `Rplot1.png' @ error/png.c/ReadPNGImage/4125.**

convert: unable to open image 'Rplot2.png': No such file or directory @ error/blob.c/OpenBlob/3093.
convert: unable to open file `Rplot2.png' @ error/png.c/ReadPNGImage/4125.
convert: unable to open image 'Rplot3.png': No such file or directory @ error/blob.c/OpenBlob/3093.
convert: unable to open file `Rplot3.png' @ error/png.c/ReadPNGImage/4125.
convert: unable to open image 'Rplot4.png': No such file or directory @ error/blob.c/OpenBlob/3093.
convert: unable to open file `Rplot4.png' @ error/png.c/ReadPNGImage/4125.
convert: unable to open image 'Rplot5.png': No such file or directory @ error/blob.c/OpenBlob/3093.
convert: unable to open file `Rplot5.png' @ error/png.c/ReadPNGImage/4125.
convert: unable to open image 'Rplot6.png': No such file or directory @ error/blob.c/OpenBlob/3093.
convert: unable to open file `Rplot6.png' @ error/png.c/ReadPNGImage/4125.
convert: unable to open image 'Rplot7.png': No such file or directory @ error/blob.c/OpenBlob/3093.
convert: unable to open file `Rplot7.png' @ error/png.c/ReadPNGImage/4125.
convert: unable to open image 'Rplot8.png': No such file or directory @ error/blob.c/OpenBlob/3093.
convert: unable to open file `Rplot8.png' @ error/png.c/ReadPNGImage/4125.
convert: unable to open image 'Rplot9.png': No such file or directory @ error/blob.c/OpenBlob/3093.
convert: unable to open file `Rplot9.png' @ error/png.c/ReadPNGImage/4125.
convert: no images defined `multiples.gif' @ error/convert.c/ConvertImageCommand/3254.
**an error occurred in the conversion... see Notes in ?im.convert
Error in file(file, "rb") : cannot open the connection**

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
