### ISSUE TITLE
Request/Question

### ISSUE THREAD

**Issue by speedreader** [thomasp85/gganimate#5]
I'm trying to access some of the setting for exporting (codec, frame rates, bit rate, etc), do I do that through gganimate directly? Is there any comprehensive documentation? I tried using the 'animate' package's saveVideo function, but it didn't change any of the defaults from gganimate. 

Love the package. Lots of uses for this.

**Comment by dgrtwo** [comment]
Yes; you can set options through the [ani.options](http://www.inside-r.org/packages/cran/animation/docs/ani.options) function in the animation package. Those arguments can also be passed directly to the `gg_animate` function (the `...`), since it passes them on to the `saveVideo`, `saveGIF`, etc functions from animation. I'll try to make this clearer in the function documentation!

If you also want to pass extra arguments to ffmpeg when creating an mp4 or avi video, you can also use `other.opts`, see [saveVideo](http://www.inside-r.org/packages/cran/animation/docs/saveVideo).
