### ISSUE TITLE
Unexpected output when using gganimate with geom extension, but not when using animation::saveGIF

### ISSUE THREAD

**Issue by JoGall** [thomasp85/gganimate#58]
I'm trying to use a `frame` aesthetic with a `geom` extension, [`ggforce::geom_voronoi_*`](https://github.com/thomasp85/ggforce/blob/master/R/voronoi.R), but getting a rather unexpected output.

![voronoi_gganimate](https://user-images.githubusercontent.com/17113779/36253272-ef81e5b4-123e-11e8-8591-7b9f303a6520.gif)

However, my animation works as expected when creating `ggplot`s individually in a `for` loop and calling `animation::save*` directly, which I understand `gganimate` uses for creating animations.

![voronoi_animation](https://user-images.githubusercontent.com/17113779/36253281-f7020580-123e-11e8-900b-09dfdf64ae5c.gif)

I guess this might be an issue with the `geom` extension more than anything  — I had a similar issue using [`geom_convexhull`](https://github.com/cmartin/ggConvexHull/blob/master/R/geom_convexhull.R) but not when manually calculating convex hulls using `chull` and plotting using `geom_polygon` — but I'd appreciate it if you could point me in a direction I could take to modify the code in order to handle a `frame` aesthetic.

Thanks for a great package!

-----

Reprex:

```{r}
library(dplyr)
library(ggplot2)
library(ggforce)

# sample data
set.seed(123)
home <- lapply(1:11, function(i) {
  data.frame(x = runif(1, 0, 65) + cumsum(runif(10, -2, 2)),
             y = runif(1, 0, 68) + cumsum(runif(10, -2, 2)),
             frame = 1:10,
             id = i,
             team = 0)
}) %>%
  plyr::rbind.fill()

away <- lapply(1:11, function(i) {
  data.frame(x = runif(1, 50, 105) + cumsum(runif(10, -2, 2)),
             y = runif(1, 0, 68) + cumsum(runif(10, -2, 2)),
             frame = 1:10,
             id = i,
             team = 1)
}) %>%
  plyr::rbind.fill()

df <- rbind(home, away)
df$team <- as.factor(df$team)

# single frame: fine
# single frame: expected
ggplot(filter(df, frame == 1), aes(x, y)) +
  geom_point(aes(fill = team), shape = 21, col = "black", size = 5, alpha = 0.8) +
  geom_voronoi_tile(aes(fill = team), bound = c(0, 105, 0, 68), alpha = 0.25) +
  geom_voronoi_segment(bound = c(0, 105, 0, 68)) +
  guides(fill = FALSE)

# gganimate: unexpected
g <- ggplot(df, aes(x, y, frame = frame)) +
  geom_point(aes(fill = team), shape = 21, col = "black", size = 5, alpha = 0.8) +
  geom_voronoi_tile(aes(fill = team), bound = c(0, 105, 0, 68), alpha = 0.25) +
  geom_voronoi_segment(bound = c(0, 105, 0, 68)) +
  guides(fill = FALSE)

gganimate::gganimate(g, interval = 0.2, "voronoi_gganimate.gif")

# animation::saveGIF: unexpected
animation::saveGIF({
  for(i in 1:max(df$frame)) {
    g <- ggplot(filter(df, frame == i), aes(x, y)) +
      geom_point(aes(fill = team), shape = 21, col = "black", size = 5, alpha = 0.8) +
      geom_voronoi_tile(aes(fill = team), bound = c(0, 105, 0, 68), alpha = 0.25) +
      geom_voronoi_segment(bound = c(0, 105, 0, 68)) +
      guides(fill = FALSE)
    print(g)
  }
  }, ani.options = animation::ani.options(ani.width = 630, ani.height = 408, interval = 0.2), movie.name = "voronoi_animation.gif")
```

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
