### ISSUE TITLE
'C:\Program' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by steveharoz** [thomasp85/gganimate#59]
I get this error when `gganimate` is called.

```r
# code from the example
library(gapminder)
library(ggplot2)
library(gganimate)
p <- ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, color = continent, frame = year)) +
  geom_point()
gganimate(p)
```

`> 'C:\Program' is not recognized as an internal or external command, operable program or batch file.`

**Comment by popovs** [comment]
This has been discussed in #54, #45, & #22 - something in those threads could help?

**Comment by dkholo** [comment]
Do we have an ETA on this? I am not able to run a sample code on the home page after installing all pre-requisites:
Executing: 
"C:\Program Files\ImageMagick-7.0.7-Q16\convert.exe -loop 0 -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png
    Rplot7.png Rplot8.png Rplot9.png Rplot10.png Rplot11.png Rplot12.png "file6c10112c6123.gif""
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
an error occurred in the conversion... see Notes in ?im.convert
Error in file(file, "rb") : cannot open the connection
In addition: Warning messages:
1: running command 'C:\WINDOWS\system32\cmd.exe /c "C:\Program Files\ImageMagick-7.0.7-Q16\convert.exe -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png Rplot11.png Rplot12.png "file6c10112c6123.gif""' had status 1 
2: In cmd.fun(convert) :
  '"C:\Program Files\ImageMagick-7.0.7-Q16\convert.exe -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png Rplot11.png Rplot12.png "file6c10112c6123.gif""' execution failed with error code 1
3: running command '"C:\Program Files\ImageMagick-7.0.7-Q16\convert.exe -loop 0  -delay 100 Rplot1.png Rplot2.png Rplot3.png Rplot4.png Rplot5.png Rplot6.png Rplot7.png Rplot8.png Rplot9.png Rplot10.png Rplot11.png Rplot12.png "file6c10112c6123.gif""' had status 127 
4: In file(file, "rb") :

**Comment by dkholo** [comment]
I was really hoping that this package would allow me to animate complex network charts :(

**Comment by dkholo** [comment]
It started working out of a sudden.

**Comment by dkholo** [comment]
Package is working as expected. This is brilliant idea to use frame as a temporal dimension. I am going to try use this package for dynamic network chart animations if possible.

**Comment by ondrejzacha** [comment]
another workaround is to reinstall ImageMagick to a different location with no spaces in path -  i.e. C:\ImageMagick\ImageMagick-7.0.7-Q16

**Comment by panzercy** [comment]
@dkholo, what did you do before it works?
@ondrejzacha where can I modify the install directory of ImageMagick?

Thanks guys

**Comment by dkholo** [comment]
The code worked after machine restart. I have not taken any specific actions.

**Comment by ondrejzacha** [comment]
@panzercy that is only possible as one of the steps during the reinstallation

**Comment by antaldaniel** [comment]
I find the code very difficult to follow, but I think that the file path is not normalized somewhere to windows (see [normalize_path](https://stat.ethz.ch/R-manual/R-devel/library/base/html/normalizePath.html) )

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
