### ISSUE TITLE
GraphicsMagick  instead of ImageMagick

### ISSUE THREAD

**Issue by juanpide** [thomasp85/gganimate#8]
Hello.

Could you add an example (and the options) working with GraphicsMagick, please?

I've tried with
animation::ani.options( convert="gm convert")
and animation::ani.options(convert="gm.exe convert")
My GraphicsMagick is in the path.
I've also tried with the full path to the executable.

But it doesn't work, gganimate still tries to find ImageMagick, that is supposed to be slower and older.

Regards.

**Comment by dgrtwo** [comment]
This is an issue with the animation package, and it looks like it was partially solved in [this commit](https://github.com/yihui/animation/commit/85a902bf3dcf9d7a4675cb43028d6eddb58d32a3). Looks like this can be fully solved by doing two things:
1. Install the development version of the animation package using the devtools package:
   
   ```
   devtools::install_github("yihui/animation")
   ```
2. Keep the ani.options convert to its default of `convert`, and instead pass `convert = "gm convert"` to the `gg_animate` function directly:

```
library(animation)
library(ggplot2)
library(gganimate)

# this line is not necessary if you're in a fresh R session, only if you have
previously set `ani.options(convert = "gm convert")`:
ani.options(convert = "convert")

p <- ggplot(mtcars, aes(wt, mpg, frame = am)) + geom_point()
gg_animate(p, outfile = "outfile.gif", convert = "gm convert")
```

I'll try to submit a fix for why setting `ani.options(convert = "gm convert")` doesn't work. Let me know if this current workaround works for you.

**Comment by juanpide** [comment]
Could you provide another example to try, please?
The example above doesn't produce any error, but it only produces two alternating empty frames.

**Comment by dgrtwo** [comment]
@skanskan Apologies, I forgot to add `geom_point()` to the above example. It is now fixed above. (You can also use the ones in the README).

**Comment by juanpide** [comment]
It works well, thank you.  
I'll try diferent options.

**Comment by juanpide** [comment]
How would you translate this animation to gganimate?

saveGIF( for (i in 0:10) barplot(prop.table(table(rbinom(10000,2^i,0.3)))),
 interval = 0.5, convert = "gm convert")  

I mean, something with not many steps (temporal files, data.frames... )

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
