### ISSUE TITLE
saving file to gif in windows leads to savepath error

### ISSUE THREAD

**Issue by RMHogervorst** [thomasp85/gganimate#9]
example:

``` r
gg_animate(p, "output.gif")
```

gives me the following output:

```
Output at: D:\Docs\Documents\folder/output.gif
opening gganimate file stored at
Error in shell.exec(file) : invalid 'file' argument
```

It seems it adds a forwardslash automaticaly. which doesn't work in windows. 
I'm not sure where the save function is in the scripts, but I advice replacing filepaths with the
file.path() function.

**Comment by RMHogervorst** [comment]
I got the example from the readme. 

the gg_animate_save(p, "output.gif") function does produce a file.
I doesn't display anything though.
(added the file to this thread)
![output](https://cloud.githubusercontent.com/assets/9538040/13092627/47f09fc4-d501-11e5-8c82-8c59155adc1a.gif)

**Comment by dgrtwo** [comment]
What's interesting is that gganimate (and just as importantly, the animation package that it wraps) does use file.path. But on my (Parallels) Windows machine, `file.path("hello", "world")` actually returns `"hello/world"`, so that won't solve this.

This has to do with the way `autobrowse` works on Windows, I'm going to look into it more. Could you confirm that the code `gg_animate(p, "output.gif")` did actually save `output.gif`, even if it gave an error afterwards?

**Comment by RMHogervorst** [comment]
`gg_animate(p, "output.gif")`  does produce a valid and functioning output file. 

and with this error:

``` r
opening gganimate file stored at
Error in shell.exec(file) : invalid 'file' argument
```

**Comment by RMHogervorst** [comment]
furthermore the animate package also has errors on my machine

**Comment by WadeDavis** [comment]
I am facing the exact same issues on a Windows. Everything else appears to work with gganimate, but gives an error when you try to pass a filename.

**Comment by dgrtwo** [comment]
We are finishing a complete rewrite of gganimate undertaken by Thomas Pedersen, with massive breaking changes to the API (this will come with a version bump to 1.0.0; currently 0.9.9.9999). This fixes many existing bugs and installation difficulties, and offers a more intuitive grammar of graphics.

As a result I'm closing almost all open issues, since they aren't relevant to the new version (bug reports in particular no longer apply). I apologize for any inconvenience in updating your existing code, but the new version of gganimate will be well worth the effort.

* If you are still interested in this issue and believe it is relevant to the new version of gganimate, you can reopen it!
* If you'd like to continue using the old gganimate version (which we do not recommend, as it will not be maintained), you can [install from this release](https://github.com/dgrtwo/gganimate/releases/tag/v0.1.1) using the following code:

      devtools::install_github("dgrtwo/gganimate", ref = "v0.1.1”)
